"""Azure Database for PostgreSQL Flexible Server.

Provisions a Burstable B1ms Flexible Server running PostgreSQL 16, a database
named ``skreg``, a randomly generated admin password, and a Kubernetes Secret
``skreg-db`` (namespace ``skreg``) whose ``DATABASE_URL`` key holds the
composed DSN. Compute components consume ``DatabaseContract`` and never need
to know the underlying Azure resource names.
"""

from __future__ import annotations

import pulumi
import pulumi_azure_native.dbforpostgresql as dbforpostgresql
import pulumi_kubernetes as k8s
import pulumi_random as random

from skreg_infra.contracts import DatabaseContract

_SECRET_NAME = "skreg-db"  # noqa: S105
_SECRET_KEY = "DATABASE_URL"  # noqa: S105
_DB_NAME = "skreg"
_ADMIN_LOGIN = "skreg"
_NAMESPACE = "skreg"


class AzurePgDatabase(pulumi.ComponentResource):
    """Azure PostgreSQL Flexible Server with a K8s DSN Secret.

    The admin password is generated by ``pulumi_random.RandomPassword`` and
    never leaves Pulumi state. The Kubernetes Secret ``skreg-db`` is created
    in the ``skreg`` namespace and consumed by the application via the
    ``DATABASE_URL`` environment variable.
    """

    def __init__(
        self,
        name: str,
        resource_group_name: str,
        location: str = "eastus",
        opts: pulumi.ResourceOptions | None = None,
    ) -> None:
        super().__init__("skreg:azure:PgDatabase", name, {}, opts)

        password = random.RandomPassword(
            f"{name}-password",
            length=32,
            special=True,
            override_special="!#$%&*()-_=+[]{}<>:?",
            opts=pulumi.ResourceOptions(parent=self),
        )

        server = dbforpostgresql.Server(
            f"{name}-server",
            resource_group_name=resource_group_name,
            location=location,
            administrator_login=_ADMIN_LOGIN,
            administrator_login_password=password.result,
            version="16",
            sku=dbforpostgresql.SkuArgs(
                name="Standard_B1ms",
                tier=dbforpostgresql.SkuTier.BURSTABLE,
            ),
            storage=dbforpostgresql.StorageArgs(storage_size_gb=32),
            backup=dbforpostgresql.BackupArgs(
                backup_retention_days=7,
                geo_redundant_backup=dbforpostgresql.GeoRedundantBackupEnum.DISABLED,
            ),
            opts=pulumi.ResourceOptions(parent=self),
        )

        dbforpostgresql.Database(
            f"{name}-db",
            resource_group_name=resource_group_name,
            server_name=server.name,
            database_name=_DB_NAME,
            opts=pulumi.ResourceOptions(parent=self, depends_on=[server]),
        )

        dsn = pulumi.Output.all(server.fully_qualified_domain_name, password.result).apply(
            lambda args: (
                f"postgresql://{_ADMIN_LOGIN}:{args[1]}@{args[0]}:5432/{_DB_NAME}?sslmode=require"
            )
        )

        k8s.core.v1.Secret(
            f"{name}-secret",
            metadata=k8s.meta.v1.ObjectMetaArgs(
                name=_SECRET_NAME,
                namespace=_NAMESPACE,
            ),
            string_data={_SECRET_KEY: dsn},
            opts=pulumi.ResourceOptions(parent=self, depends_on=[server]),
        )

        self._contract = DatabaseContract(
            dsn_secret_name=_SECRET_NAME,
            dsn_secret_key=_SECRET_KEY,
        )
        self.register_outputs({"secret_name": _SECRET_NAME})

    @property
    def contract(self) -> DatabaseContract:
        return self._contract
